version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "./wait-for-it.sh db:3306; uwsgi --ini /var/www/html/uwsgi.ini"
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST="%"
      - TZ="Asia/Tokyo"