version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "python manage.py migrate --settings=config.settings.production; uwsgi --ini /var/www/html/uwsgi.ini"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - PORT=8000
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"