version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8000:8000"
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    command: uwsgi --ini /var/www/html/uwsgi.ini
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    volumes:
      - .:/var/www/html
    ports:
      - "3031:3031"